spring:
  application:
    name: simple-planning-tool
  datasource:
    url: jdbc:postgresql://localhost:5432/planning_tool
    username: user
    password: password
#    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true


